/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSetNewPasswordRouteImport } from './routes/_auth/set-new-password'
import { Route as AuthOauthCallbackRouteImport } from './routes/_auth/oauth-callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppInstallmentsRouteImport } from './routes/_app.installments'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppChecksRouteImport } from './routes/_app.checks'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetNewPasswordRoute = AuthSetNewPasswordRouteImport.update({
  id: '/set-new-password',
  path: '/set-new-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallmentsRoute = AppInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppChecksRoute = AppChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/cases': typeof AppCasesRoute
  '/checks': typeof AppChecksRoute
  '/documents': typeof AppDocumentsRoute
  '/installments': typeof AppInstallmentsRoute
  '/kanban': typeof AppKanbanRoute
  '/parties': typeof AppPartiesRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/set-new-password': typeof AuthSetNewPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/cases': typeof AppCasesRoute
  '/checks': typeof AppChecksRoute
  '/documents': typeof AppDocumentsRoute
  '/installments': typeof AppInstallmentsRoute
  '/kanban': typeof AppKanbanRoute
  '/parties': typeof AppPartiesRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/set-new-password': typeof AuthSetNewPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/checks': typeof AppChecksRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/installments': typeof AppInstallmentsRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/parties': typeof AppPartiesRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/_auth/set-new-password': typeof AuthSetNewPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/cases'
    | '/checks'
    | '/documents'
    | '/installments'
    | '/kanban'
    | '/parties'
    | '/payments'
    | '/settings'
    | '/forgot-password'
    | '/oauth-callback'
    | '/set-new-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/cases'
    | '/checks'
    | '/documents'
    | '/installments'
    | '/kanban'
    | '/parties'
    | '/payments'
    | '/settings'
    | '/forgot-password'
    | '/oauth-callback'
    | '/set-new-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/verify-otp'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/calendar'
    | '/_app/cases'
    | '/_app/checks'
    | '/_app/documents'
    | '/_app/installments'
    | '/_app/kanban'
    | '/_app/parties'
    | '/_app/payments'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/oauth-callback'
    | '/_auth/set-new-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_auth/verify-otp'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/set-new-password': {
      id: '/_auth/set-new-password'
      path: '/set-new-password'
      fullPath: '/set-new-password'
      preLoaderRoute: typeof AuthSetNewPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/oauth-callback': {
      id: '/_auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installments': {
      id: '/_app/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AppInstallmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checks': {
      id: '/_app/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof AppChecksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCasesRoute: typeof AppCasesRoute
  AppChecksRoute: typeof AppChecksRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInstallmentsRoute: typeof AppInstallmentsRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCasesRoute: AppCasesRoute,
  AppChecksRoute: AppChecksRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInstallmentsRoute: AppInstallmentsRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthSetNewPasswordRoute: typeof AuthSetNewPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthSetNewPasswordRoute: AuthSetNewPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
